### ISSUE TITLE
Current master breaks docker-compose example

### ISSUE THREAD

**Issue by aeneasr** [ory/kratos-selfservice-ui-node#18]
I am not able to run the current master of this repository in the Docker Compose Quickstart example, instead I see this error message:

```
kratos-selfservice-ui-node_1  | _http_outgoing.js:535
kratos-selfservice-ui-node_1  |     throw new ERR_HTTP_HEADERS_SENT('set');
kratos-selfservice-ui-node_1  |     ^
kratos-selfservice-ui-node_1  | 
kratos-selfservice-ui-node_1  | Error [ERR_HTTP_HEADERS_SENT]: Cannot set headers after they are sent to the client
kratos-selfservice-ui-node_1  |     at ServerResponse.setHeader (_http_outgoing.js:535:11)
kratos-selfservice-ui-node_1  |     at ServerResponse.header (/usr/src/app/node_modules/express/lib/response.js:771:10)
kratos-selfservice-ui-node_1  |     at ServerResponse.send (/usr/src/app/node_modules/express/lib/response.js:170:12)
kratos-selfservice-ui-node_1  |     at done (/usr/src/app/node_modules/express/lib/response.js:1008:10)
kratos-selfservice-ui-node_1  |     at Immediate._onImmediate (/usr/src/app/node_modules/express-handlebars/lib/utils.js:26:13)
kratos-selfservice-ui-node_1  |     at processImmediate (internal/timers.js:456:21) {
kratos-selfservice-ui-node_1  |   code: 'ERR_HTTP_HEADERS_SENT'
kratos-selfservice-ui-node_1  | }
```

**Comment by aeneasr** [comment]
Restarting everything helped, but we need to investigate why this error happened.

**Comment by zepatrik** [comment]
could not reproduce
