### ISSUE TITLE
Internal error when following quickstart (issue with @ory/integrations v0.1.2)

### ISSUE THREAD

**Issue by timdrysdale** [ory/kratos-selfservice-ui-node#181]
### Preflight checklist

- [X] I could not find a solution in the existing issues, docs, nor discussions.
- [X] I agree to follow this project's [Code of Conduct](https://github.com/ory/kratos-selfservice-ui-node/blob/master/CODE_OF_CONDUCT.md).
- [X] I have read and am following this repository's [Contribution Guidelines](https://github.com/ory/kratos-selfservice-ui-node/blob/master/CONTRIBUTING.md).
- [ ] This issue affects my [Ory Cloud](https://www.ory.sh/) project.
- [X] I have joined the [Ory Community Slack](https://slack.ory.sh).
- [X] I am signed up to the [Ory Security Patch Newsletter](https://ory.us10.list-manage.com/subscribe?u=ffb1a878e4ec6c0ed312a3480&id=f605a41b53).

### Describe the bug

I get an internal server error 500 when attempting to sign in, or sign up using this standalone app, together with kratos service running in Docker (I know I could just use the quickstart version of the app on its own, but wanted to try this way too, so as to prepare for doing development, then hit this error). Fixed by making location modification to @ory/integrations as detailed below, and subsequently this app works as expected when served from host machine whilst running Kratos quickstart with docker. 

### Reproducing the bug

1. Run the quickstart
```
git clone https://github.com/ory/kratos.git
cd kratos
git checkout v0.9.0-alpha.3
docker-compose -f quickstart.yml -f quickstart-standalone.yml --build --force-recreate
```
2. Kill the standalone ui container
```
docker container kill <ID of kratos-selfservice-ui-node container>
```
3. Build & run  the standalone app
```
git clone https://github.com/ory/kratos-selfservice-ui-node.git
cd kratos-selfservice-ui-node
npm install
npm run build
npm start
```
4. Navigate to localhost:4455/welcome and then click on either sign in, or sign up (same problem either way) - a page reporting an internal error has occurred and a pair of empty curly brackets in the text display area.

### Relevant log output

```shell
Log from `npm start`

TypeError: Cannot read property 'text' of undefined
    at Object.getNodeLabel (/home/tim/sources/kratos-selfservice-ui-node/node_modules/@ory/integrations/src/ui/index.ts:29:31)
    at Object.wrapper (/home/tim/sources/kratos-selfservice-ui-node/node_modules/handlebars/lib/handlebars/internal/wrapHelper.js:10:19)
    at Object.eval (eval at createFunctionContext (/home/tim/sources/kratos-selfservice-ui-node/node_modules/handlebars/lib/handlebars/compiler/javascript-compiler.js:265:23), <anonymous>:13:114)
    at main (/home/tim/sources/kratos-selfservice-ui-node/node_modules/handlebars/lib/handlebars/runtime.js:230:22)
    at ret (/home/tim/sources/kratos-selfservice-ui-node/node_modules/handlebars/lib/handlebars/runtime.js:250:12)
    at ret (/home/tim/sources/kratos-selfservice-ui-node/node_modules/handlebars/lib/handlebars/compiler/compiler.js:548:21)
    at Object.invokePartial (/home/tim/sources/kratos-selfservice-ui-node/node_modules/handlebars/lib/handlebars/runtime.js:405:12)
    at Object.invokePartialWrapper [as invokePartial] (/home/tim/sources/kratos-selfservice-ui-node/node_modules/handlebars/lib/handlebars/runtime.js:82:39)
    at eval (eval at createFunctionContext (/home/tim/sources/kratos-selfservice-ui-node/node_modules/handlebars/lib/handlebars/compiler/javascript-compiler.js:265:23), <anonymous>:10:31)
    at prog (/home/tim/sources/kratos-selfservice-ui-node/node_modules/handlebars/lib/handlebars/runtime.js:333:12)
```
```


### Relevant configuration

```yml
as per [quickstart](https://github.com/ory/kratos-selfservice-ui-node#test-with-ory-kratos) for docker (ignoring the bit about `make quickstart-dev` which fails due to missing `quickstart`)
```

### Version

v0.9.0-alpha.3

### On which operating system are you observing this issue?

Linux

### In which environment are you deploying?

Other

### Additional Context

@ory/integrations is pinned at v0.1.2 in `package.json`. 
 
Fixed locally by modifying the function `getNodeLabel` in node_modules/@ory/integrations/src/ui/index.js
```
const getNodeLabel = (node) => {
  const attributes = node.attributes;
  if (isUiNodeAnchorAttributes(attributes)) {
    return attributes.title.text;
  }
  if (isUiNodeImageAttributes(attributes)) {
    if (node.meta.label){
    return node.meta.label.text;
}
  }
  if (isUiNodeInputAttributes(attributes)) {
    if (attributes.label) {
      return attributes.label.text;
    }
  }
  if (node.meta.label) {
  return node.meta.label.text; 
}
return ''
};
```

I also had a look at just upgrading to the latest version of `integrations`, but that had a similar issue (although with typescript version it seemed the other way around, with unneeded use of ?. in a return)

Wondering if the combination of Kratos in docker and standalone UI is an edge case that is not tested, hence these minor issues with handling potentially null values slipped through testing ...?

**Comment by safizn** [comment]
I did encounter an internal error with setting it up in Kubernetes. Turns out it was permissions issues because the NodeJS user in the container didn't have sufficient permissions. Changing the deployment to  securityContext configuration fixed it.
