### ISSUE TITLE
Login doesn't work

### ISSUE THREAD

**Issue by lotigara** [ory/kratos-selfservice-ui-node#339]
### Preflight checklist

- [X] I could not find a solution in the existing issues, docs, nor discussions.
- [X] I agree to follow this project's [Code of Conduct](https://github.com/ory/kratos-selfservice-ui-node/blob/master/CODE_OF_CONDUCT.md).
- [X] I have read and am following this repository's [Contribution Guidelines](https://github.com/ory/kratos-selfservice-ui-node/blob/master/CONTRIBUTING.md).
- [ ] I have joined the [Ory Community Slack](https://slack.ory.sh).
- [ ] I am signed up to the [Ory Security Patch Newsletter](https://ory.us10.list-manage.com/subscribe?u=ffb1a878e4ec6c0ed312a3480&id=f605a41b53).

### Describe the bug

I followed these instructions for self-hosting: https://www.ory.sh/docs/kratos/guides/deploy-kratos-example (Note that I used SQLite3 because it's easier to setup), but when I need to login to my Kratos instance (https://accounts.example.com/auth/login), I see the following error:
```
TypeError: Converting circular structure to JSON
    --> starting at object with constructor 'Socket'
    |     property '_httpMessage' -> object with constructor 'ClientRequest'
    --- property 'socket' closes the circle
    at JSON.stringify (<anonymous>)
    at UserErrorCard$1 (/opt/uinode/ui/node_modules/@ory/elements-markup/dist/index.umd.js:104:36900)
    at _t (/opt/uinode/ui/node_modules/@ory/elements-markup/dist/index.umd.js:169:3633)
    at Nl (/opt/uinode/ui/node_modules/@ory/elements-markup/dist/index.umd.js:169:4508)
    at Ha (/opt/uinode/ui/node_modules/@ory/elements-markup/dist/index.umd.js:169:7515)
    at Wa (/opt/uinode/ui/node_modules/@ory/elements-markup/dist/index.umd.js:169:9191)
    at Rr (/opt/uinode/ui/node_modules/@ory/elements-markup/dist/index.umd.js:169:8960)
    at Ro (/opt/uinode/ui/node_modules/@ory/elements-markup/dist/index.umd.js:169:7183)
    at Ha (/opt/uinode/ui/node_modules/@ory/elements-markup/dist/index.umd.js:169:7943)
    at Wa (/opt/uinode/ui/node_modules/@ory/elements-markup/dist/index.umd.js:169:9191)
```

### Reproducing the bug

1. Launch both Kratos and `uinode` services (`service kratos start; service uinode start`);
2. Open your browser at `https://accounts.example.com/auth/login`
3. See the error above.

### Relevant log output

```shell
Jun 08 13:21:17 lotigara npm[2734649]: > @ory/kratos-selfservice-ui-node@0.15.0 start
Jun 08 13:21:17 lotigara npm[2734649]: > nodemon
Jun 08 13:21:17 lotigara npm[2734661]: [nodemon] 3.0.1
Jun 08 13:21:17 lotigara npm[2734661]: [nodemon] to restart at any time, enter `rs`
Jun 08 13:21:17 lotigara npm[2734661]: [nodemon] watching path(s): src/**/*
Jun 08 13:21:17 lotigara npm[2734661]: [nodemon] watching extensions: ts
Jun 08 13:21:17 lotigara npm[2734661]: [nodemon] starting `ts-node ./src/index.ts`
Jun 08 13:21:19 lotigara npm[2734675]: Listening on http://0.0.0.0:3000
Jun 08 13:21:23 lotigara npm[2734675]: AxiosError: connect ECONNREFUSED ::1:4433
Jun 08 13:21:23 lotigara npm[2734675]:     at Function.AxiosError.from (/opt/uinode/ui/node_modules/axios/lib/core/AxiosError.js:89:14)
Jun 08 13:21:23 lotigara npm[2734675]:     at RedirectableRequest.handleRequestError (/opt/uinode/ui/node_modules/axios/lib/adapters/http.js:610:25)
Jun 08 13:21:23 lotigara npm[2734675]:     at RedirectableRequest.emit (node:events:517:28)
Jun 08 13:21:23 lotigara npm[2734675]:     at RedirectableRequest.emit (node:domain:489:12)
Jun 08 13:21:23 lotigara npm[2734675]:     at ClientRequest.eventHandlers.<computed> (/opt/uinode/ui/node_modules/follow-redirects/index.js:38:24)
Jun 08 13:21:23 lotigara npm[2734675]:     at ClientRequest.emit (node:events:517:28)
Jun 08 13:21:23 lotigara npm[2734675]:     at ClientRequest.emit (node:domain:489:12)
Jun 08 13:21:23 lotigara npm[2734675]:     at Socket.socketErrorListener (node:_http_client:501:9)
Jun 08 13:21:23 lotigara npm[2734675]:     at Socket.emit (node:events:517:28)
Jun 08 13:21:23 lotigara npm[2734675]:     at Socket.emit (node:domain:489:12)
Jun 08 13:21:23 lotigara npm[2734675]:     at Axios.request (/opt/uinode/ui/node_modules/axios/lib/core/Axios.js:45:41)
Jun 08 13:21:23 lotigara npm[2734675]:     at processTicksAndRejections (node:internal/process/task_queues:95:5) {
Jun 08 13:21:23 lotigara npm[2734675]:   port: 4433,
Jun 08 13:21:23 lotigara npm[2734675]:   address: '::1',
Jun 08 13:21:23 lotigara npm[2734675]:   syscall: 'connect',
Jun 08 13:21:23 lotigara npm[2734675]:   code: 'ECONNREFUSED',
Jun 08 13:21:23 lotigara npm[2734675]:   errno: -111,
Jun 08 13:21:23 lotigara npm[2734675]:   config: {
Jun 08 13:21:23 lotigara npm[2734675]:     transitional: {
Jun 08 13:21:23 lotigara npm[2734675]:       silentJSONParsing: true,
Jun 08 13:21:23 lotigara npm[2734675]:       forcedJSONParsing: true,
Jun 08 13:21:23 lotigara npm[2734675]:       clarifyTimeoutError: false
Jun 08 13:21:23 lotigara npm[2734675]:     },
Jun 08 13:21:23 lotigara npm[2734675]:     adapter: [ 'xhr', 'http' ],
Jun 08 13:21:23 lotigara npm[2734675]:     transformRequest: [ [Function: transformRequest] ],
Jun 08 13:21:23 lotigara npm[2734675]:     transformResponse: [ [Function: transformResponse] ],
Jun 08 13:21:23 lotigara npm[2734675]:     timeout: 0,
Jun 08 13:21:23 lotigara npm[2734675]:     xsrfCookieName: 'XSRF-TOKEN',
Jun 08 13:21:23 lotigara npm[2734675]:     xsrfHeaderName: 'X-XSRF-TOKEN',
Jun 08 13:21:23 lotigara npm[2734675]:     maxContentLength: -1,
Jun 08 13:21:23 lotigara npm[2734675]:     maxBodyLength: -1,
Jun 08 13:21:23 lotigara npm[2734675]:     env: { FormData: [Function], Blob: [class Blob] },
Jun 08 13:21:23 lotigara npm[2734675]:     validateStatus: [Function: validateStatus],
Jun 08 13:21:23 lotigara npm[2734675]:     headers: Object [AxiosHeaders] {
Jun 08 13:21:23 lotigara npm[2734675]:       Accept: 'application/json, text/plain, */*',
Jun 08 13:21:23 lotigara npm[2734675]:       'Content-Type': undefined,
Jun 08 13:21:23 lotigara npm[2734675]:       Cookie: 'csrf_token_0ef567daff7f2f241089ce82879e96f035777f0652869bace3df42e12141a54c=pClbikW+oOEPsw8o4kHOSk5wadZeCtR9DY5vnPuFDH0=; i_like_gitea=d6fbb4efca9e4dbf; _csrf=1t49cdn-ALxpVf7j01d6gAJdrTg6MTcxNzg0MTU2NDUyOTMwMDYzNQ',
Jun 08 13:21:23 lotigara npm[2734675]:       'User-Agent': 'axios/1.6.7',
Jun 08 13:21:23 lotigara npm[2734675]:       'Accept-Encoding': 'gzip, compress, deflate, br'
Jun 08 13:21:23 lotigara npm[2734675]:     },
Jun 08 13:21:23 lotigara npm[2734675]:     method: 'get',
Jun 08 13:21:23 lotigara npm[2734675]:     url: 'http://localhost:4433/self-service/login/flows?id=ef638cb3-1d8e-4ef3-9aa7-778e018f772d',
Jun 08 13:21:23 lotigara npm[2734675]:     data: undefined
Jun 08 13:21:23 lotigara npm[2734675]:   },
Jun 08 13:21:23 lotigara npm[2734675]:   request: <ref *1> Writable {
Jun 08 13:21:23 lotigara npm[2734675]:     _writableState: WritableState {
Jun 08 13:21:23 lotigara npm[2734675]:       objectMode: false,
Jun 08 13:21:23 lotigara npm[2734675]:       highWaterMark: 16384,
Jun 08 13:21:23 lotigara npm[2734675]:       finalCalled: false,
Jun 08 13:21:23 lotigara npm[2734675]:       needDrain: false,
Jun 08 13:21:23 lotigara npm[2734675]:       ending: false,
Jun 08 13:21:23 lotigara npm[2734675]:       ended: false,
Jun 08 13:21:23 lotigara npm[2734675]:       finished: false,
Jun 08 13:21:23 lotigara npm[2734675]:       destroyed: false,
Jun 08 13:21:23 lotigara npm[2734675]:       decodeStrings: true,
Jun 08 13:21:23 lotigara npm[2734675]:       defaultEncoding: 'utf8',
Jun 08 13:21:23 lotigara npm[2734675]:       length: 0,
Jun 08 13:21:23 lotigara npm[2734675]:       writing: false,
Jun 08 13:21:23 lotigara npm[2734675]:       corked: 0,
Jun 08 13:21:23 lotigara npm[2734675]:       sync: true,
Jun 08 13:21:23 lotigara npm[2734675]:       bufferProcessing: false,
Jun 08 13:21:23 lotigara npm[2734675]:       onwrite: [Function: bound onwrite],
Jun 08 13:21:23 lotigara npm[2734675]:       writecb: null,
Jun 08 13:21:23 lotigara npm[2734675]:       writelen: 0,
Jun 08 13:21:23 lotigara npm[2734675]:       afterWriteTickInfo: null,
Jun 08 13:21:23 lotigara npm[2734675]:       buffered: [],
Jun 08 13:21:23 lotigara npm[2734675]:       bufferedIndex: 0,
Jun 08 13:21:23 lotigara npm[2734675]:       allBuffers: true,
Jun 08 13:21:23 lotigara npm[2734675]:       allNoop: true,
Jun 08 13:21:23 lotigara npm[2734675]:       pendingcb: 0,
Jun 08 13:21:23 lotigara npm[2734675]:       constructed: true,
Jun 08 13:21:23 lotigara npm[2734675]:       prefinished: false,
Jun 08 13:21:23 lotigara npm[2734675]:       errorEmitted: false,
Jun 08 13:21:23 lotigara npm[2734675]:       emitClose: true,
Jun 08 13:21:23 lotigara npm[2734675]:       autoDestroy: true,
Jun 08 13:21:23 lotigara npm[2734675]:       errored: null,
Jun 08 13:21:23 lotigara npm[2734675]:       closed: false,
Jun 08 13:21:23 lotigara npm[2734675]:       closeEmitted: false,
Jun 08 13:21:23 lotigara npm[2734675]:       [Symbol(kOnFinished)]: []
Jun 08 13:21:23 lotigara npm[2734675]:     },
Jun 08 13:21:23 lotigara npm[2734675]:     _events: [Object: null prototype] {
Jun 08 13:21:23 lotigara npm[2734675]:       response: [Function: handleResponse],
Jun 08 13:21:23 lotigara npm[2734675]:       error: [Function: handleRequestError],
Jun 08 13:21:23 lotigara npm[2734675]:       socket: [Function: handleRequestSocket]
Jun 08 13:21:23 lotigara npm[2734675]:     },
Jun 08 13:21:23 lotigara npm[2734675]:     _eventsCount: 3,
Jun 08 13:21:23 lotigara npm[2734675]:     _maxListeners: undefined,
Jun 08 13:21:23 lotigara npm[2734675]:     _options: {
Jun 08 13:21:23 lotigara npm[2734675]:       maxRedirects: 21,
Jun 08 13:21:23 lotigara npm[2734675]:       maxBodyLength: Infinity,
Jun 08 13:21:23 lotigara npm[2734675]:       protocol: 'http:',
Jun 08 13:21:23 lotigara npm[2734675]:       path: '/self-service/login/flows?id=ef638cb3-1d8e-4ef3-9aa7-778e018f772d',
Jun 08 13:21:23 lotigara npm[2734675]:       method: 'GET',
Jun 08 13:21:23 lotigara npm[2734675]:       headers: [Object: null prototype],
Jun 08 13:21:23 lotigara npm[2734675]:       agents: [Object],
Jun 08 13:21:23 lotigara npm[2734675]:       auth: undefined,
Jun 08 13:21:23 lotigara npm[2734675]:       family: undefined,
Jun 08 13:21:23 lotigara npm[2734675]:       beforeRedirect: [Function: dispatchBeforeRedirect],
Jun 08 13:21:23 lotigara npm[2734675]:       beforeRedirects: [Object],
Jun 08 13:21:23 lotigara npm[2734675]:       hostname: 'localhost',
Jun 08 13:21:23 lotigara npm[2734675]:       port: '4433',
Jun 08 13:21:23 lotigara npm[2734675]:       agent: undefined,
Jun 08 13:21:23 lotigara npm[2734675]:       nativeProtocols: [Object],
Jun 08 13:21:23 lotigara npm[2734675]:       pathname: '/self-service/login/flows',
Jun 08 13:21:23 lotigara npm[2734675]:       search: '?id=ef638cb3-1d8e-4ef3-9aa7-778e018f772d'
Jun 08 13:21:23 lotigara npm[2734675]:     },
Jun 08 13:21:23 lotigara npm[2734675]:     _ended: true,
Jun 08 13:21:23 lotigara npm[2734675]:     _ending: true,
Jun 08 13:21:23 lotigara npm[2734675]:     _redirectCount: 0,
Jun 08 13:21:23 lotigara npm[2734675]:     _redirects: [],
Jun 08 13:21:23 lotigara npm[2734675]:     _requestBodyLength: 0,
Jun 08 13:21:23 lotigara npm[2734675]:     _requestBodyBuffers: [],
Jun 08 13:21:23 lotigara npm[2734675]:     _onNativeResponse: [Function (anonymous)],
Jun 08 13:21:23 lotigara npm[2734675]:     _currentRequest: ClientRequest {
Jun 08 13:21:23 lotigara npm[2734675]:       _events: [Object: null prototype],
Jun 08 13:21:23 lotigara npm[2734675]:       _eventsCount: 7,
Jun 08 13:21:23 lotigara npm[2734675]:       _maxListeners: undefined,
Jun 08 13:21:23 lotigara npm[2734675]:       outputData: [],
Jun 08 13:21:23 lotigara npm[2734675]:       outputSize: 0,
Jun 08 13:21:23 lotigara npm[2734675]:       writable: true,
Jun 08 13:21:23 lotigara npm[2734675]:       destroyed: false,
Jun 08 13:21:23 lotigara npm[2734675]:       _last: true,
Jun 08 13:21:23 lotigara npm[2734675]:       chunkedEncoding: false,
Jun 08 13:21:23 lotigara npm[2734675]:       shouldKeepAlive: false,
Jun 08 13:21:23 lotigara npm[2734675]:       maxRequestsOnConnectionReached: false,
Jun 08 13:21:23 lotigara npm[2734675]:       _defaultKeepAlive: true,
Jun 08 13:21:23 lotigara npm[2734675]:       useChunkedEncodingByDefault: false,
Jun 08 13:21:23 lotigara npm[2734675]:       sendDate: false,
Jun 08 13:21:23 lotigara npm[2734675]:       _removedConnection: false,
Jun 08 13:21:23 lotigara npm[2734675]:       _removedContLen: false,
Jun 08 13:21:23 lotigara npm[2734675]:       _removedTE: false,
Jun 08 13:21:23 lotigara npm[2734675]:       strictContentLength: false,
Jun 08 13:21:23 lotigara npm[2734675]:       _contentLength: 0,
Jun 08 13:21:23 lotigara npm[2734675]:       _hasBody: true,
Jun 08 13:21:23 lotigara npm[2734675]:       _trailer: '',
Jun 08 13:21:23 lotigara npm[2734675]:       finished: true,
Jun 08 13:21:23 lotigara npm[2734675]:       _headerSent: true,
Jun 08 13:21:23 lotigara npm[2734675]:       _closed: false,
Jun 08 13:21:23 lotigara npm[2734675]:       socket: [Socket],
Jun 08 13:21:23 lotigara npm[2734675]:       _header: 'GET /self-service/login/flows?id=ef638cb3-1d8e-4ef3-9aa7-778e018f772d HTTP/1.1\r\n' +
Jun 08 13:21:23 lotigara npm[2734675]:         'Accept: application/json, text/plain, */*\r\n' +
Jun 08 13:21:23 lotigara npm[2734675]:         'Cookie: csrf_token_0ef567daff7f2f241089ce82879e96f035777f0652869bace3df42e12141a54c=pClbikW+oOEPsw8o4kHOSk5wadZeCtR9DY5vnPuFDH0=; i_like_gitea=d6fbb4efca9e4dbf; _csrf=1t49cdn-ALxpVf7j01d6gAJdrTg6MTcxNzg0MTU2NDUyOTMwMDYzNQ\r\n' +
Jun 08 13:21:23 lotigara npm[2734675]:         'User-Agent: axios/1.6.7\r\n' +
Jun 08 13:21:23 lotigara npm[2734675]:         'Accept-Encoding: gzip, compress, deflate, br\r\n' +
Jun 08 13:21:23 lotigara npm[2734675]:         'Host: localhost:4433\r\n' +
Jun 08 13:21:23 lotigara npm[2734675]:         'Connection: close\r\n' +
Jun 08 13:21:23 lotigara npm[2734675]:         '\r\n',
Jun 08 13:21:23 lotigara npm[2734675]:       _keepAliveTimeout: 0,
Jun 08 13:21:23 lotigara npm[2734675]:       _onPendingData: [Function: nop],
Jun 08 13:21:23 lotigara npm[2734675]:       agent: [Agent],
Jun 08 13:21:23 lotigara npm[2734675]:       socketPath: undefined,
Jun 08 13:21:23 lotigara npm[2734675]:       method: 'GET',
Jun 08 13:21:23 lotigara npm[2734675]:       maxHeaderSize: undefined,
Jun 08 13:21:23 lotigara npm[2734675]:       insecureHTTPParser: undefined,
Jun 08 13:21:23 lotigara npm[2734675]:       joinDuplicateHeaders: undefined,
Jun 08 13:21:23 lotigara npm[2734675]:       path: '/self-service/login/flows?id=ef638cb3-1d8e-4ef3-9aa7-778e018f772d',
Jun 08 13:21:23 lotigara npm[2734675]:       _ended: false,
Jun 08 13:21:23 lotigara npm[2734675]:       res: null,
Jun 08 13:21:23 lotigara npm[2734675]:       aborted: false,
Jun 08 13:21:23 lotigara npm[2734675]:       timeoutCb: null,
Jun 08 13:21:23 lotigara npm[2734675]:       upgradeOrConnect: false,
Jun 08 13:21:23 lotigara npm[2734675]:       parser: null,
Jun 08 13:21:23 lotigara npm[2734675]:       maxHeadersCount: null,
Jun 08 13:21:23 lotigara npm[2734675]:       reusedSocket: false,
Jun 08 13:21:23 lotigara npm[2734675]:       host: 'localhost',
Jun 08 13:21:23 lotigara npm[2734675]:       protocol: 'http:',
Jun 08 13:21:23 lotigara npm[2734675]:       _redirectable: [Circular *1],
Jun 08 13:21:23 lotigara npm[2734675]:       [Symbol(kCapture)]: false,
Jun 08 13:21:23 lotigara npm[2734675]:       [Symbol(kBytesWritten)]: 0,
Jun 08 13:21:23 lotigara npm[2734675]:       [Symbol(kNeedDrain)]: false,
Jun 08 13:21:23 lotigara npm[2734675]:       [Symbol(corked)]: 0,
Jun 08 13:21:23 lotigara npm[2734675]:       [Symbol(kOutHeaders)]: [Object: null prototype],
Jun 08 13:21:23 lotigara npm[2734675]:       [Symbol(errored)]: null,
Jun 08 13:21:23 lotigara npm[2734675]:       [Symbol(kHighWaterMark)]: 16384,
Jun 08 13:21:23 lotigara npm[2734675]:       [Symbol(kRejectNonStandardBodyWrites)]: false,
Jun 08 13:21:23 lotigara npm[2734675]:       [Symbol(kUniqueHeaders)]: null
Jun 08 13:21:23 lotigara npm[2734675]:     },
Jun 08 13:21:23 lotigara npm[2734675]:     _currentUrl: 'http://localhost:4433/self-service/login/flows?id=ef638cb3-1d8e-4ef3-9aa7-778e018f772d',
Jun 08 13:21:23 lotigara npm[2734675]:     [Symbol(kCapture)]: false
Jun 08 13:21:23 lotigara npm[2734675]:   },
Jun 08 13:21:23 lotigara npm[2734675]:   cause: Error: connect ECONNREFUSED ::1:4433
Jun 08 13:21:23 lotigara npm[2734675]:       at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1549:16) {
Jun 08 13:21:23 lotigara npm[2734675]:     errno: -111,
Jun 08 13:21:23 lotigara npm[2734675]:     code: 'ECONNREFUSED',
Jun 08 13:21:23 lotigara npm[2734675]:     syscall: 'connect',
Jun 08 13:21:23 lotigara npm[2734675]:     address: '::1',
Jun 08 13:21:23 lotigara npm[2734675]:     port: 4433
Jun 08 13:21:23 lotigara npm[2734675]:   }
Jun 08 13:21:23 lotigara npm[2734675]: } Error: connect ECONNREFUSED ::1:4433
Jun 08 13:21:23 lotigara npm[2734675]:     at Function.AxiosError.from (/opt/uinode/ui/node_modules/axios/lib/core/AxiosError.js:89:14)
Jun 08 13:21:23 lotigara npm[2734675]:     at RedirectableRequest.handleRequestError (/opt/uinode/ui/node_modules/axios/lib/adapters/http.js:610:25)
Jun 08 13:21:23 lotigara npm[2734675]:     at RedirectableRequest.emit (node:events:517:28)
Jun 08 13:21:23 lotigara npm[2734675]:     at RedirectableRequest.emit (node:domain:489:12)
Jun 08 13:21:23 lotigara npm[2734675]:     at ClientRequest.eventHandlers.<computed> (/opt/uinode/ui/node_modules/follow-redirects/index.js:38:24)
Jun 08 13:21:23 lotigara npm[2734675]:     at ClientRequest.emit (node:events:517:28)
Jun 08 13:21:23 lotigara npm[2734675]:     at ClientRequest.emit (node:domain:489:12)
Jun 08 13:21:23 lotigara npm[2734675]:     at Socket.socketErrorListener (node:_http_client:501:9)
Jun 08 13:21:23 lotigara npm[2734675]:     at Socket.emit (node:events:517:28)
Jun 08 13:21:23 lotigara npm[2734675]:     at Socket.emit (node:domain:489:12)
Jun 08 13:21:23 lotigara npm[2734675]:     at Axios.request (/opt/uinode/ui/node_modules/axios/lib/core/Axios.js:45:41)
Jun 08 13:21:23 lotigara npm[2734675]:     at processTicksAndRejections (node:internal/process/task_queues:95:5)
Jun 08 13:21:23 lotigara npm[2734675]: {"level":"info","message":"HTTP GET /login?flow=ef638cb3-1d8e-4ef3-9aa7-778e018f772d","meta":{"req":{"headers":{"accept":"text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.7","accept-encoding":"gzip, deflate, br, zstd","accept-language":"ru-RU,ru;q=0.9,en-US;q=0.8,en;q=0.7","cache-control":"max-age=0","connection":"close","cookie":"csrf_token_0ef567daff7f2f241089ce82879e96f035777f0652869bace3df42e12141a54c=pClbikW+oOEPsw8o4kHOSk5wadZeCtR9DY5vnPuFDH0=; i_like_gitea=d6fbb4efca9e4dbf; _csrf=1t49cdn-ALxpVf7j01d6gAJdrTg6MTcxNzg0MTU2NDUyOTMwMDYzNQ","host":"accounts.lotigara.ru","priority":"u=0, i","sec-ch-ua":"\"Chromium\";v=\"125\", \"Not.A/Brand\";v=\"24\"","sec-ch-ua-mobile":"?0","sec-ch-ua-platform":"\"Linux\"","sec-fetch-dest":"document","sec-fetch-mode":"navigate","sec-fetch-site":"none","sec-fetch-user":"?1","upgrade-insecure-requests":"1","user-agent":"Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/125.0.0.0 Safari/537.36","x-forwarded-for":"192.168.1.1","x-real-ip":"192.168.1.1"},"httpVersion":"1.0","method":"GET","originalUrl":"/login?flow=ef638cb3-1d8e-4ef3-9aa7-778e018f772d","query":{"flow":"ef638cb3-1d8e-4ef3-9aa7-778e018f772d"},"url":"/login?flow=ef638cb3-1d8e-4ef3-9aa7-778e018f772d"},"res":{"statusCode":500},"responseTime":52}}
Jun 08 13:21:23 lotigara npm[2734675]: TypeError: Converting circular structure to JSON
Jun 08 13:21:23 lotigara npm[2734675]:     --> starting at object with constructor 'Socket'
Jun 08 13:21:23 lotigara npm[2734675]:     |     property '_httpMessage' -> object with constructor 'ClientRequest'
Jun 08 13:21:23 lotigara npm[2734675]:     --- property 'socket' closes the circle
Jun 08 13:21:23 lotigara npm[2734675]:     at JSON.stringify (<anonymous>)
Jun 08 13:21:23 lotigara npm[2734675]:     at UserErrorCard$1 (/opt/uinode/ui/node_modules/@ory/elements-markup/dist/index.umd.js:104:36900)
Jun 08 13:21:23 lotigara npm[2734675]:     at _t (/opt/uinode/ui/node_modules/@ory/elements-markup/dist/index.umd.js:169:3633)
Jun 08 13:21:23 lotigara npm[2734675]:     at Nl (/opt/uinode/ui/node_modules/@ory/elements-markup/dist/index.umd.js:169:4508)
Jun 08 13:21:23 lotigara npm[2734675]:     at Ha (/opt/uinode/ui/node_modules/@ory/elements-markup/dist/index.umd.js:169:7515)
Jun 08 13:21:23 lotigara npm[2734675]:     at Wa (/opt/uinode/ui/node_modules/@ory/elements-markup/dist/index.umd.js:169:9191)
Jun 08 13:21:23 lotigara npm[2734675]:     at Rr (/opt/uinode/ui/node_modules/@ory/elements-markup/dist/index.umd.js:169:8960)
Jun 08 13:21:23 lotigara npm[2734675]:     at Ro (/opt/uinode/ui/node_modules/@ory/elements-markup/dist/index.umd.js:169:7183)
Jun 08 13:21:23 lotigara npm[2734675]:     at Ha (/opt/uinode/ui/node_modules/@ory/elements-markup/dist/index.umd.js:169:7943)
Jun 08 13:21:23 lotigara npm[2734675]:     at Wa (/opt/uinode/ui/node_modules/@ory/elements-markup/dist/index.umd.js:169:9191)
Jun 08 13:50:02 lotigara npm[2734675]: {"level":"info","message":"HTTP GET /login","meta":{"req":{"headers":{"accept":"*/*","connection":"close","host":"accounts.lotigara.ru","user-agent":"curl/7.88.1","x-forwarded-for":"192.168.1.1","x-real-ip":"192.168.1.1"},"httpVersion":"1.0","method":"GET","originalUrl":"/login","query":{},"url":"/login"},"res":{"statusCode":303},"responseTime":3}}
```

### Relevant configuration

```yml
version: v0.13.0

dsn: sqlite:///opt/kratos/kratos.sqlite?_fk=true

serve:
  public:
    base_url: https://accounts.example.com/
    host: 127.0.0.1
    cors:
      enabled: true
  admin:
    base_url: http://kratos:4434/
    host: 127.0.0.1

selfservice:
  default_browser_return_url: https://accounts.example.com/auth
  allowed_return_urls:
    - https://accounts.example.com
    - http://localhost:19006/Callback
    - exp://localhost:8081/--/Callback

  methods:
    password:
      enabled: true
    totp:
      config:
        issuer: Kratos
      enabled: true
    lookup_secret:
      enabled: true
    link:
      enabled: true
    code:
      enabled: true

  flows:
    error:
      ui_url: https://accounts.example.com/auth/errors

    settings:
      ui_url: https://accounts.example.com/auth/settings
      privileged_session_max_age: 15m
      required_aal: highest_available

    recovery:
      enabled: true
      ui_url: https://accounts.example.com/auth/recovery
      use: code

    verification:
      enabled: true
      ui_url: https://accounts.example.com/auth/verification
      use: code
      after:
        default_browser_return_url: https://accounts.example.com/auth

    logout:
      after:
        default_browser_return_url: https://accounts.example.com/auth/login

    login:
      ui_url: https://accounts.example.com/auth/login
      lifespan: 10m

    registration:
      lifespan: 10m
      ui_url: https://accounts.example.com/auth/registration
      after:
        password:
          hooks:
            - hook: session
            - hook: show_verification_ui

log:
  level: debug
  format: text
  leak_sensitive_values: true

secrets:
  cookie:
    - PLEASE-CHANGE-ME-I-AM-VERY-INSECURE
  cipher:
    - 32-LONG-SECRET-NOT-SECURE-AT-ALL

ciphers:
  algorithm: xchacha20-poly1305

hashers:
  algorithm: bcrypt
  bcrypt:
    cost: 8

identity:
  default_schema_id: default
  schemas:
    - id: default
      url: file:///opt/kratos/config/identity.schema.json

courier:
  smtp:
    connection_uri: smtps://test:test@mailslurper:1025/?skip_ssl_verify=true

feature_flags:
  use_continue_with_transitions: true
```

### Version

v1.2.0-sqlite

### On which operating system are you observing this issue?

Linux

### In which environment are you deploying?

Binary

### Additional Context

I use Debian 12.5.

**Comment by JackySu** [comment]
the same error for me, unfortunately it seems no response yet
