### ISSUE TITLE
Error Setup with UnauthorizedError: No authorization token was found

### ISSUE THREAD

**Issue by ycgambo** [ory/kratos-selfservice-ui-node#77]
**Describe the bug**

following the install guide on https://www.ory.sh/kratos/docs/quickstart/

start build docker image with source code in master

**To Reproduce**

```
git clone https://github.com/ory/kratos.git
git checkout master
make quickstart-dev
```

go to http://127.0.0.1:4455/dashboard

**Expected behavior**

show login screen

**Actual behavior**

shows

An error occurred

```
{
  "name": "UnauthorizedError",
  "message": "No authorization token was found",
  "code": "credentials_required",
  "status": 401,
  "inner": {
    "message": "No authorization token was found"
  }
}
```

logs
```
kratos-selfservice-ui-node_1  | UnauthorizedError: No authorization token was found
kratos-selfservice-ui-node_1  |     at middleware (/usr/src/app/node_modules/express-jwt/lib/index.js:79:21)
kratos-selfservice-ui-node_1  |     at Layer.handle [as handle_request] (/usr/src/app/node_modules/express/lib/router/layer.js:95:5)
kratos-selfservice-ui-node_1  |     at next (/usr/src/app/node_modules/express/lib/router/route.js:137:13)
kratos-selfservice-ui-node_1  |     at Route.dispatch (/usr/src/app/node_modules/express/lib/router/route.js:112:3)
kratos-selfservice-ui-node_1  |     at Layer.handle [as handle_request] (/usr/src/app/node_modules/express/lib/router/layer.js:95:5)
kratos-selfservice-ui-node_1  |     at /usr/src/app/node_modules/express/lib/router/index.js:281:22
kratos-selfservice-ui-node_1  |     at Function.process_params (/usr/src/app/node_modules/express/lib/router/index.js:335:12)
kratos-selfservice-ui-node_1  |     at next (/usr/src/app/node_modules/express/lib/router/index.js:275:10)
kratos-selfservice-ui-node_1  |     at SendStream.error (/usr/src/app/node_modules/serve-static/index.js:121:7)
kratos-selfservice-ui-node_1  |     at SendStream.emit (events.js:321:20)
kratos-selfservice-ui-node_1  | GET /dashboard 500 11571 - 714.033 ms
kratos-selfservice-ui-node_1  | GET /form.css 304 - - 20.003 ms
kratos-selfservice-ui-node_1  | GET /index.css 304 - - 15.942 ms
kratos-selfservice-ui-node_1  | GET /auth.css 304 - - 1.758 ms
kratos-selfservice-ui-node_1  | GET /typography.css 304 - - 2.589 ms
kratos-selfservice-ui-node_1  | GET /favicon.ico 302 22 - 11.979 ms
```

**Environment**

master branch with hash 6f750047

**Comment by ycgambo** [comment]
reference: #38

**Comment by zepatrik** [comment]
When you use
```
$ make quickstart-dev
```
in kratos you also have to use the master of the selfservice ui node, i.e. run 
```
$ cd $(mktmp -d)
$ git clone git@github.com:ory/kratos-selfservice-ui-node.git .
$ make docker
```
If you want to use the latest release, just use
```
$ make quickstart
```
in kratos.

**Comment by ykuzma1** [comment]
I am still experiencing this issue @zepatrik. `make quickstart` _is_ the command giving me the error referenced.

**Comment by ycgambo** [comment]
build docker image from this repo works.
either `make quickstart` or `make quickstart-dev` in kratos

**Comment by zepatrik** [comment]
I'm sorry, I forgot that we released the selfservice ui early, please use

Setup:
```
cd $(mktmp -d)
git clone git@github.com:ory/kratos.git .
git checkout v0.4.6-alpha.1
```

Run:
```
docker pull oryd/kratos:v0.4.6-alpha.1-sqlite
docker tag oryd/kratos:v0.4.6-alpha.1-sqlite oryd/kratos:latest-sqlite
docker pull oryd/kratos-selfservice-ui-node:v0.4.6-alpha.1
docker tag oryd/kratos-selfservice-ui-node:v0.4.6-alpha.1  oryd/kratos-selfservice-ui-node:latest
docker-compose -f quickstart.yml -f quickstart-standalone.yml up --build --force-recreate
```

instead of `make quickstart` for now. Also your changes @ykuzma1 are not necessary, you just forgot to `git checkout v0.4.6-alpha.1`

**Comment by zepatrik** [comment]
It should automatically work again with the next release of kratos, then the versions will be aligned again.
